### PR TITLE
MNT: Re-rendered with conda-smithy 2.3.2

### PR DESCRIPTION
**Pull request by synapticarbors**
Re-render feedstock and hopefully general missing Windows 3.6 builds necessary for:

https://github.com/conda-forge/staged-recipes/pull/3175

### CODE REVIEW

**Comment by sannykr** [comment]
Is this ready to merge?

**Comment by synapticarbors** [comment]
@jakirkham  -- If @kwilcox or @daf isn't available to merge this, Could you take a look at this? It's a simple re-render to get windows py36 binaries built.

**Comment by daf** [comment]
Sorry @synapticarbors, was away this weekend.  Now merged.

**Comment by synapticarbors** [comment]
@daf -- Thanks for looking at this. Much appreciated.

**Pull request merged**
